### PR TITLE
HC-380, HC-383, HC-384: update to celery v5.1.2, accept json content to receive revokes, mitigate autoscaling API throttling

### PR DESCRIPTION
**Pull request by pymonger**
This PR updates HySDS core to use celery v5.1.2 and additionally updates the `celeryconfig.py.tmpl` template to include `json` as acceptable content, which is the format of broadcasted revoke payloads.
This was tested in NISAR using the NASA demo pipeline (dev-e2e + ALOS L0B processed to RSLC, GSLC and GCOV).

### CODE REVIEW

**Review by DustinKLo — DISMISSED** [review]

**Review by mcayanan — APPROVED** [review]
LGTM. Seems like with this update, we'll need to update the custom celery configs on both the swot and nisar side. We have a few sitting on that side of the repo.

**Comment by pymonger** [comment]
@mcayanan yes. I have a separate PR for nisar-pcm that syncs the celeryconfig.py update.

**Review by DustinKLo — APPROVED** [review]
LGTM 👍  but ill wait for @mcayanan as a 2nd opinion

**Review by mcayanan — APPROVED** [review]
LGTM too

**Review by NamrataM — APPROVED** [review]
LGTM!

**Pull request merged**
