### PR TITLE
HC-284: remove bloat from context

### PR DESCRIPTION
**Pull request by pymonger**
Details on this PR is located at https://hysds-core.atlassian.net/browse/HC-284.
Additionally, this also lowers the default number of `user_rules_*` celery workers running on factotum.

Testing done in NISAR I&T NITT-02 test (1488 NEN files).

### CODE REVIEW

**Review by DustinKLo — APPROVED** [review]
LGTM 👍 
should we add these changes to `supervisor.conf.factotum` in `nisar-pcm` as well?

**Review by mcayanan — DISMISSED** [review]
LGTM too. swot will need to remember to add this to its custom supervisord as well.

**Comment by pymonger** [comment]
@DustinKLo @mcayanan: could you rereview? I pushed a few more updates.
@DustinKLo: yes, i will include the update in my nisar-pcm NSDS-997 branch.

**Review by DustinKLo — DISMISSED** [review]
👍  LGTM again

**Review by mcayanan — APPROVED** [review]
Ditto!

**Review by DustinKLo — APPROVED** [review]
👍 LGTM once more

**Pull request merged**
