### PR TITLE
fixed get_job_status function, renamed id to _id

### PR DESCRIPTION
**Pull request by DustinKLo**

### CODE REVIEW

**Comment by DustinKLo** [comment]
@mcayanan ticket with research: https://hysds-core.atlassian.net/browse/HC-183

**Comment by mcayanan** [comment]
Hey @DustinKLo. Changes look good to me. Just to piggyback off the conversation we were having on slack, could you also please update the `celeryconfig.py.tmpl` file and add a `METRICS_ES_URL` setting? I think its a simple change that can be added to this PR if you agree.

**Comment by DustinKLo** [comment]
@mcayanan  sure, added `METRICS_ES_URL` to celeryconfig

why do we have a separate template variable for `PVT_IP` and `ES_PVT_IP`
for example, `MOZART_ES_PVT_IP` and `MOZART_PVT_IP`

**Comment by mcayanan** [comment]
Thanks for adding that @mcayanan. PR looks good on my end. In regards to why there's a `PVT_IP` and `ES_PVT_IP`, I'm afraid I don't know. I think @pymonger may know the reason.

**Comment by pymonger** [comment]
> Thanks for adding that @mcayanan. PR looks good on my end. In regards to why there's a `PVT_IP` and `ES_PVT_IP`, I'm afraid I don't know. I think @pymonger may know the reason.

@DustinKLo @mcayanan : in most cases the ES server is installed on mozart but in cases where ES is installed on a different instance, those 2 variables will be different. In the past death valley tests on ARIA, we configured a cluster in "trinity mode" where we broke out mozart's ES, rabbitmq, and redis services out to 3 different instances to help with scaling out to 8000+ worker instances. This necessitated defining those different variables.

**Pull request merged**
